export const errorMessages = {
  VALIDATION_ERROR: "Validation Error",
  ITEM_NOT_FOUND: "Item not found",
  DATABASE_ERROR: "A database error occurred",
  MISSING_FIELDS: "Required fields are missing",
  UNEXPECTED_ERROR: "An unexpected error occurred",
  ACCESS_DENIED: "Database access denied. Please check your credentials.",
  DATABASE_NOT_FOUND: "The specified database was not found.",
  DATABASE_CONNECTION_FAILED: "Failed to connect to the database.",
  TABLE_CREATION_FAILED: "Failed to create the 'items' table.",
  TABLE_EXISTS_CHECK_FAILED: "Failed to check if the 'items' table exists.",
  DATABASE_INITIALIZATION_FAILED: "Error initializing the database.",
  NAME_TOO_LONG: "Name must be at most 100 characters long.",
  DESCRIPTION_TOO_LONG: "Description must be at most 500 characters long.",
  TITLE_REQUIRED: "Job title is required",
  TITLE_TOO_LONG: "Job title cannot exceed 255 characters",
  COMPANY_REQUIRED: "Company name is required",
  COMPANY_TOO_LONG: "Company name cannot exceed 255 characters",
  LOCATION_REQUIRED: "Location is required",
  LOCATION_TOO_LONG: "Location cannot exceed 100 characters",
  EXPERIENCE_LEVEL_INVALID: "Experience level must be Entry-Level, Mid-Level, or Senior-Level",
  SALARY_POSITIVE: "Salary must be a positive number",
  INDUSTRY_TOO_LONG: "Industry name cannot exceed 100 characters",
  UPDATE_FIELD_REQUIRED: "At least one field must be provided for update",
  JOB_NOT_FOUND: "Job not found",
  JOB_INDEX_CREATION_FAILED: "Failed to create job index in Elasticsearch",
  JOB_INDEX_NOT_FOUND: "Job index not found in Elasticsearch",
  MUST_BE_NUMBER: "Salary must be a number or empty",
};
